### ISSUE TITLE
DMP CMS - Production deployment

### ISSUE THREAD

**Issue by karntrehan** [Code4GovTech/DMP-CMS-Backend-API#19]
- [x] Deployment of CMS BE
- [x] Deployment of CMS FE
- [x] Cleanup of supabase test data
- [x] Prod issue updates in supabase
- [x] Dev testing

**Comment by MohitNSamagra** [comment]
- DB to be cleared - 19th 
- PT ticket data to be added - 19th

**Comment by MohitNSamagra** [comment]
- https fix - @sasi2312 - 20th
- csv upload of data - @MohitNSamagra - 20th
- PM UAT - 20th

**Comment by karntrehan** [comment]
- Some APIs still failing - @sasi2312 and @jaanbaaz to work on this. 
- Once dev is fixed, changes to be pulled to prod - @karntrehan

**Comment by karntrehan** [comment]
WIP

**Comment by MohitNSamagra** [comment]
- PM tested - Not able to add issues under same owner but diff repo
- Can be deployed to prod - to check with @karntrehan

**Comment by VedantKhairnar** [comment]
- The required changes around weekly and issues data fix were merged in dev, yet to be merged in prod @karntrehan 
- staging cron is stopped and prod cron duration is increased to 3 hrs

**Comment by MohitNSamagra** [comment]
- ready to be deployed to prod

**Comment by MohitNSamagra** [comment]
- Deployed to prod
